CREATE TABLE LOCATIONS (
  location_id INT PRIMARY KEY,
  region VARCHAR (50) NOT NULL,
  country VARCHAR (15) NOT NULL,
  population INT8,
  density FLOAT
)

CREATE TABLE MAKE_DETAILS (
  MAKE_id INT PRIMARY KEY,
  MAKE_NAME VARCHAR (30) NOT NULL,
  MAKE_TYPE VARCHAR (15) NOT NULL
)

CREATE TABLE STOLEN_VEHICLES (
  VEHICLE_ID INT PRIMARY KEY,
  VEHICLE_TYPE VARCHAR (50),
  MAKE_ID INT,
  MODEL_YEAR INT,
  VEHICLE_DESC VARCHAR (50),
  COLOR VARCHAR (15),
  DATE_STOLEN DATE,
  LOCATION_ID INT
)

---for foreign keys

ALTER TABLE STOLEN_VEHICLES
ADD CONSTRAINT LOCATIONS_FKEY
FOREIGN KEY (LOCATION_ID) 
REFERENCES LOCATIONS(LOCATION_ID);

ALTER TABLE STOLEN_VEHICLES
ADD CONSTRAINT MAKE_FKEY
FOREIGN KEY (MAKE_ID) 
REFERENCES MAKE_DETAILS(MAKE_ID);

---deleting null values

DELETE FROM STOLEN_VEHICLES
WHERE 
    VEHICLE_ID IS NULL OR VEHICLE_TYPE IS NULL OR MAKE_ID IS NULL OR 
    MODEL_YEAR IS NULL OR VEHICLE_DESC IS NULL OR COLOR IS NULL OR 
    DATE_STOLEN IS NULL OR LOCATION_ID IS NULL;



SELECT *
FROM LOCATIONS

SELECT *
FROM MAKE_DETAILS

SELECT *
FROM STOLEN_VEHICLES